### ISSUE TITLE
Unistall script is required

### ISSUE THREAD

**Issue by Slony** [google-marketing-solutions/crmint#153]
A CLI command that uninstalls the CRMint instance is required in order to revert a Cloud Project to its original state.

**Comment by dulacp** [comment]
Fair point. It was also one of the reason why we migrated to Terraform for deploying CRMint 3, so that we can leverage `terraform destroy` to clean everything related to our project.

I'm working on a PR to include this functionality into the CRMint CLI too for those you are not familiar with Terraform.

**Comment by blackwire** [comment]
Closing this as resolved due to the above mentioned PR being merged now.
