### ISSUE TITLE
Error Loading Data in CRMint

### ISSUE THREAD

**Issue by crandroi** [google-marketing-solutions/crmint#469]
Hi,

I deployed CRMint via bash <(curl -Ls https://raw.githubusercontent.com/instant-bqml/crmint/master/scripts/install.sh) master --bundle and I'm getting "There is error after loading data" on the pipelines tab. 

![image](https://github.com/google-marketing-solutions/crmint/assets/58442677/bbe0a1a7-7d7f-4c61-95e4-6394054b3e3b)

We've run CRMint before on a separate project without issues, so I'm not sure if this is a recent change. This is the only error clear error I see in console: Uncaught (in promise): Http failure during parsing for https://instant-bqml-398214.ue.r.appspot.com/api/configuration

Any thoughts as to the issue?

Thanks

**Comment by crandroi** [comment]
Thanks! On retry I see the following error message:

![image](https://github.com/google-marketing-solutions/crmint/assets/58442677/5e8faa92-2caf-4de0-8f02-9b09b38156e7)

The rest of the frontend deployment steps succeed without issue. Is that fixable, or should I just try the Cloud Run version?

**Comment by instant-bqml** [comment]
A couple options. 

1. You can get more detail on what the issue is by removing some commented python code in [shared.py](https://github.com/instant-bqml/crmint/blob/master/cli/utils/shared.py#L102) starting at line 102 up to line 107. Once you've made that change to execute those lines during deployment, execute this command in your cloud shell: `source ~/.bashrc`. Then execute `crmint cloud deploy --frontend`. This will retry the deployment of frontend with the additional comments. This might give you more details as to why this step is failing but I'm unsure why this would be happening in your Cloud Shell specifically.
2. Sometimes if you're using Cloud Shell it can be outdated for 1 reason or another. Switching to [Ephemeral Mode](https://cloud.google.com/shell/docs/using-cloud-shell#choose_ephemeral_mode) can sometimes help. I'd still suggest uncommenting the lines in python and retrying the deployment in Ephemeral Mode to see if it works smoother.
3. Deploy using Cloud Run by executing this command `source <(curl -Ls https://raw.githubusercontent.com/google-marketing-solutions/crmint/master/scripts/install.sh) master && crmint bundle install`. I would definitely recommend executing this in Ephemeral Mode so that you have a clean starting point in your cloud shell. Also, please keep in mind to deploy using Cloud Run you must be a Google Cloud project that is part of an Organization or have a Cloud Identity. Before deploying via Cloud Run, you should also clean up your App Engine deployment. So first start by doing `source ~/.bashrc` and then run `crmint cloud uninstall`. At that point, I'd switch over to Ephemeral mode and retry deployment via Cloud Run.

**Comment by instant-bqml** [comment]
This also appears to have been an error relating to the Node Version Manager which is set to `16.16.0` in [cloud.py](https://github.com/instant-bqml/crmint/blob/master/cli/commands/cloud.py#L776).

You can resolve this by updating `16.16.0` to `20.5.0`.

I'm pushing this change to `instant-bqml/crmint/master` so that this shouldn't impact future App Engine deployments.

**Comment by crandroi** [comment]
You beat me to it, I was able to resolve the frontend issue by updating the node version. Running the full setup in ephemeral mode resolved the error loading data though.

Thanks for the help and for pushing the fix!
